### ISSUE TITLE
How to get the source code of simulator?

### ISSUE THREAD

**Issue by Simon-Fuhaoyuan** [shyamsn97/mario-gpt#18]
Hi Shyam, I'm recently following this work and I want to make some extensions to the simulator. I want to know how you get the `jar` packages [here](https://github.com/shyamsn97/mario-gpt/tree/main/mario_gpt/simulator)? If the source code is not open-source, is it possible to send me a copy? Thanks in advance!

**Comment by shyamsn97** [comment]
Hey! You can find the java code here: https://github.com/shyamsn97/Mario-AI-Framework
