### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by Amin456789** [shyamsn97/mario-gpt#28]
Hi!
i love it!
will there be new enemies, levels and maybe midi music for it?

kind regards

**Comment by shyamsn97** [comment]
Hey thanks for the kind words! I’m definitely planning on adding support for additional tiles and stuff as I’ve been trying stuff on the side for a while! Midi seems a bit tougher though, but someone who knows the musicgen field would probably know better than me.

**Comment by Amin456789** [comment]
nice, thanks!

**Comment by shyamsn97** [comment]
Closed this, feel free to open this if you have more questions!
