### ISSUE TITLE
Fine-tuned tokenizer

### ISSUE THREAD

**Issue by ChinJianGin** [shyamsn97/mario-gpt#29]
Hello,
Your project is awesome, and I'm delighted to have such a fantastic project.
When I cloned your project and trained it myself, I tried to save the tokenizer like save model, but I found the tokenizer_config.json and tokenizer.json not like your config. I don't know how to resize the vocab from 50256 to 256 and set "endoftext" token to id = 0. Could you give me some tips how to fine-tune the tokenizer? I did this because when I ran trained model, I have to use your tokenizer, if I use the tokenizer that I saved decode will go wrong.

This is my tokenizer_config.json file
![image](https://github.com/shyamsn97/mario-gpt/assets/48975062/48228ffc-5d77-46f7-a23e-586991452794)

This is my tokenizer.json file
![image](https://github.com/shyamsn97/mario-gpt/assets/48975062/16056e25-41f4-46be-9f06-cf91e4025086)
![image](https://github.com/shyamsn97/mario-gpt/assets/48975062/f7267865-03ac-419c-8b65-98fb2a04452c)

**Comment by shyamsn97** [comment]
Hey! You can see an example for training in the train notebook, but here’s where I get the tokenizer ready: https://github.com/shyamsn97/mario-gpt/blob/main/mario_gpt/dataset.py#L68

**Comment by ChinJianGin** [comment]
Oh! I got it! Thank you very much for help. Have a nice day!
