### ISSUE TITLE
Generating levels for other games

### ISSUE THREAD

**Issue by erlend-sh** [shyamsn97/mario-gpt#3]
We are making an open source, tile-based game with fairly similar constraints as super Mario:
https://github.com/fishfolk/jumpy/

We’ve also made progress on procedural level generation using the Wave Function Collapse technique:
https://github.com/fishfolk/jumpy/discussions/512

I’d love to chat about ways in which we might be able to collaborate ☺️ happy to talk more here, on Discord or by email.

**Comment by shyamsn97** [comment]
Wow this is awesome! Would love to hear more about the project. Let’s chat :). My email is shyamsnair@protonmail.com
