### ISSUE TITLE
The poor performance of MarioBert

### ISSUE THREAD

**Issue by Ezio77** [shyamsn97/mario-gpt#32]
Thanks for your great work. I tried to implement MarioBERT myself, but the inpainting results were not good. I used the pre-trained model "shyamsn97/MarioBert-448-inpaint-context-length" you provided. I would appreciate it if you can give me some suggestions.

**Comment by EdwardSJ151** [comment]
Hi, I see you closed the issue, did you figure out how to improve the results? I would like to see the code you used if you dont mind
