### ISSUE TITLE
colab notebook 

### ISSUE THREAD

**Issue by pszemraj** [shyamsn97/mario-gpt#7]
HI!

I saw your paper; I think it's a fantastic project! I noticed that there isn't a colab notebook available for people to try out the code. So I took the liberty of creating one. Here's the [link to the notebook](https://colab.research.google.com/gist/pszemraj/9f5bb58c15dc121126594c44d498e7cc/mariogpt-basic-inference.ipynb)

I am also happy to contribute via PR; just let me know how you would prefer.

**Comment by shyamsn97** [comment]
Looks good, if you wanna add a link in the readme that'd be great :)

**Comment by shyamsn97** [comment]
Added a new updated colab, badge is on readme

**Comment by pszemraj** [comment]
Ah was just going to get to it! Looks good :relaxed:
